export const GET_PROD_BY_SOLD = 'GET_PROD_BY_SOLD';
export const GET_PROD_BY_DATE = 'GET_PROD_BY_DATE';
export const GET_PROD_PAGINATE = 'GET_PROD_PAGINATE';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const PRODUCT_ADD = 'PRODUCT_ADD';
export const CLEAR_PRODUCT_ADD = 'CLEAR_PRODUCT_ADD';
export const GET_PROD_BY_ID = 'GET_PROD_BY_ID';
export const CLEAR_CURRENT_PRODUCT= 'CLEAR_CURRENT_PRODUCT';

// BRANDS
export const GET_ALL_BRANDS = 'GET_ALL_BRANDS';

// NOTIFICATION
export const ERROR_GLOBAL = 'ERROR_GLOBAL';
export const SUCCESS_GLOBAL = 'SUCCESS_GLOBAL';
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';

// USER
export const AUTH_USER = 'AUTH_USER';
export const SIGN_OUT = 'SIGN_OUT';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const USER_CHANGE_EMAIL = 'USER_CHANGE_EMAIL';
export const USER_ADD_TO_CART = 'USER_ADD_TO_CART';
export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';